name: geomonitoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - scikit-learn
  - statsmodels
  - xarray
  - netcdf4
  - gdal
  - rasterio
  - geopandas
  - folium
  - jupyter
  - ipywidgets
  - tqdm
  - pyyaml
  - psutil
  - openpyxl
  - pip
  - pip:
    - geemap
    - earthengine-api
    - plotly-express
    - kaleido 